import { cloudbaseConfigurationMessage, downloadImage, getCurrentUser, initialiseCloudbase, isCloudbaseConfigured, signInWithEmail, signOut, signUpWithEmail, verifySignUpOtp } from "./cloudbase.js";
import { createSyncService, normaliseAccountRecords } from "./sync.js";

const PROJECTS=[{id:"english",name:"学个英语",color:"var(--english-color)"},{id:"lacquer",name:"做个大漆",color:"var(--lacquer-color)"},{id:"dance",name:"杂七杂八",color:"var(--misc-color)"}];
const ALLOWED_IMAGE_TYPES=new Set(["image/jpeg","image/png","image/webp","image/heic","image/heif","image/avif","image/gif"]);
const UNSUPPORTED_IMAGE_MESSAGE="不支持这种图片格式，请使用 JPEG、PNG、WebP、HEIC、HEIF、AVIF 或 GIF。";
const DB_NAME="daily-growth",DB_VERSION=3,STATE="state",MEDIA="media",LEGACY="daily-growth:v1",$=(s)=>document.querySelector(s),key=(uid)=>`account:${uid}:records`;
let db,fallback=false,data={},user,sync,activeProject,attachments=[],viewerUrl,registerMode=false,pendingSignUp,filter={applied:false,year:"",month:"",date:"",start:"",end:""},filterMode="year";
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const today=(d=new Date())=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);
const active=(r)=>r?.sync_status!=="pending_delete"&&!r?.deleted_at;
const records=(day,id,all=false)=>{const v=day?.[id],a=Array.isArray(v)?v:v?[v]:[];return all?a:a.filter(active)};
const done=(r)=>!!(r&&(Number(r.minutes)>0||r.title||r.content||r.notes||r.note||r.media?.length));
const has=(d)=>PROJECTS.some(p=>records(d,p.id).some(done));
const mins=(v)=>{v=Math.max(0,Math.round(Number(v)||0));const h=Math.floor(v/60),m=v%60;return h?`${h}小时${m?`${m}分钟`:""}`:`${m}分钟`};
const esc=(v)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c]);
const dateText=(d)=>new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"long",day:"numeric",weekday:"short"}).format(new Date(`${d}T12:00:00`));
const monthText=(d)=>new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"long"}).format(new Date(`${d}-01T12:00:00`));
const complete=(tx)=>new Promise((ok,bad)=>{tx.oncomplete=ok;tx.onerror=()=>bad(tx.error);tx.onabort=()=>bad(tx.error)});
function openDB(){return new Promise((ok,bad)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const x=r.result;if(!x.objectStoreNames.contains(STATE))x.createObjectStore(STATE);if(!x.objectStoreNames.contains(MEDIA))x.createObjectStore(MEDIA,{keyPath:"id"})};r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)})}
async function stateGet(k){if(fallback)return JSON.parse(localStorage.getItem(`daily-growth:${k}`)||"null");const tx=db.transaction(STATE,"readonly"),r=tx.objectStore(STATE).get(k),v=await new Promise((ok,bad)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)});await complete(tx);return v}
async function statePut(k,v){if(fallback)return localStorage.setItem(`daily-growth:${k}`,JSON.stringify(v));const tx=db.transaction(STATE,"readwrite");tx.objectStore(STATE).put(v,k);await complete(tx)}
async function stateKeys(){if(fallback)return Object.keys(localStorage).filter(k=>k.startsWith("daily-growth:account:")).map(k=>k.slice("daily-growth:".length));const tx=db.transaction(STATE,"readonly"),r=tx.objectStore(STATE).getAllKeys(),v=await new Promise((ok,bad)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)});await complete(tx);return v}
const recordFingerprints=(source)=>new Set(Object.entries(source||{}).flatMap(([date,day])=>Object.entries(day||{}).flatMap(([category,value])=>(Array.isArray(value)?value:value?[value]:[]).map(r=>JSON.stringify([date,category==="misc"?"dance":category,r?.title||"",Number(r?.minutes)||0,r?.content||"",r?.note??r?.notes??"",(r?.media||[]).map(x=>x.id).sort()])))));
async function inferLegacyOwner(){if(await stateGet("legacyOwnerUid"))return;const legacy=await stateGet("records")||{},legacyRecords=recordFingerprints(legacy);if(!legacyRecords.size)return;const owners=[];for(const stateKey of await stateKeys()){if(!String(stateKey).startsWith("account:")||!String(stateKey).endsWith(":records"))continue;const account=await stateGet(stateKey)||{},accountRecords=recordFingerprints(account);if([...legacyRecords].some(item=>accountRecords.has(item)))owners.push(String(stateKey).slice(8,-8))}if(owners.length===1)await statePut("legacyOwnerUid",owners[0]);else if(owners.length>1)await statePut("legacyOwnerUid","legacy-owner-conflict")}
const pendingCount=()=>Object.values(data).flatMap(day=>Object.values(day||{}).flatMap(v=>Array.isArray(v)?v:[v])).filter(r=>["pending","failed","pending_delete"].includes(r?.sync_status)).length;
async function save(){if(user){await statePut(key(user.id),data);if(!navigator.onLine)syncStatus({state:"offline",count:pendingCount()})}}
async function saveImage(x){if(fallback)throw Error("当前浏览器无法离线保存图片。");if(!user?.id)throw Error("未登录，无法保存图片缓存。");const tx=db.transaction(MEDIA,"readwrite");tx.objectStore(MEDIA).put({...x,owner_user_id:user.id});await complete(tx)}
async function getImage(id){if(!user?.id)return;if(!fallback){const tx=db.transaction(MEDIA,"readonly"),r=tx.objectStore(MEDIA).get(id),v=await new Promise((ok,bad)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)});await complete(tx);if(v?.owner_user_id===user.id&&v.blob)return v.blob}const image=Object.values(data).flatMap(day=>Object.values(day||{}).flatMap(v=>Array.isArray(v)?v:[v])).flatMap(r=>r?.media||[]).find(x=>x.id===id);if(!image?.path||!navigator.onLine)return;const blob=await downloadImage(image.path);await saveImage({...image,blob});return blob}
async function deleteImages(ids){if(fallback||!user?.id||!ids.length)return;const tx=db.transaction(MEDIA,"readwrite"),s=tx.objectStore(MEDIA);[...new Set(ids)].forEach(id=>{const r=s.get(id);r.onsuccess=()=>{if(r.result?.owner_user_id===user.id)s.delete(id)}});await complete(tx)}
async function claimImageCache(records,ownerId){if(fallback||!ownerId)return;const ids=[...new Set(Object.values(records).flatMap(day=>Object.values(day||{}).flatMap(v=>Array.isArray(v)?v:[v])).flatMap(r=>r?.media||[]).map(x=>x.id).filter(Boolean))];if(!ids.length)return;const tx=db.transaction(MEDIA,"readwrite"),s=tx.objectStore(MEDIA);ids.forEach(id=>{const r=s.get(id);r.onsuccess=()=>{if(r.result&&!r.result.owner_user_id)s.put({...r.result,owner_user_id:ownerId})}});await complete(tx)}
async function storage(){try{db=await openDB();if(!await stateGet("records")){await statePut("records",JSON.parse(localStorage.getItem(LEGACY)||"{}"));localStorage.removeItem(LEGACY)}await inferLegacyOwner()}catch(e){fallback=true;console.warn(e)}}
function streak(){let n=0,d=new Date(`${today()}T12:00:00`);while(has(data[today(d)])){n++;d.setDate(d.getDate()-1)}return n}
function clearURLs(el){(el._urls||[]).forEach(URL.revokeObjectURL);el._urls=[]}
async function images(el,list,{editable=false,onRemove}={}){clearURLs(el);const token=Symbol();el._token=token;el.replaceChildren();for(const image of list||[]){let blob=image.file;try{blob||=await getImage(image.id)}catch{}if(!blob?.type?.startsWith("image/")||el._token!==token)continue;const url=URL.createObjectURL(blob);el._urls.push(url);const item=document.createElement("div"),button=document.createElement("button"),img=document.createElement("img");item.className="media-item";button.className="image-trigger";button.type="button";img.src=url;img.alt=image.name||"打卡图片";button.append(img);button.onclick=()=>{viewerUrl=URL.createObjectURL(blob);$("#media-viewer img").src=viewerUrl;$("#media-viewer").hidden=false};item.append(button);if(editable){const remove=document.createElement("button");remove.className="media-remove";remove.textContent="×";remove.onclick=()=>onRemove(image.id);item.append(remove)}el.append(item)}}
function closeViewer(){$("#media-viewer").hidden=true;$("#media-viewer img").removeAttribute("src");if(viewerUrl)URL.revokeObjectURL(viewerUrl);viewerUrl=null}
function view(id){document.querySelectorAll(".view").forEach(x=>x.hidden=x.id!==id);document.querySelectorAll(".tab[data-view]").forEach(x=>x.classList.toggle("is-active",x.dataset.view===id))}
function renderToday(){const d=data[today()]||{},count=PROJECTS.filter(p=>records(d,p.id).some(done)).length;$("#today-label").textContent=dateText(today());$("#streak-count").textContent=streak();$("#completion-copy").textContent=count?`今天已完成 ${count} / 3 项`:"今天还未开始";const list=$("#project-list");list.replaceChildren();PROJECTS.forEach(p=>{const checked=records(d,p.id).some(done),b=document.createElement("button");b.className="project-card";b.type="button";b.style.setProperty("--project",p.color);b.innerHTML=`<span><h3>${p.name}${checked?'<span class="done-check"> ✓</span>':""}</h3><p>${checked?"今天已打卡":"点击开始打卡"}</p></span><span class="arrow">›</span>`;b.onclick=()=>openCheckin(p);list.append(b)})}
function openCheckin(p){activeProject=p;attachments=[];$("#checkin-heading").textContent=`${p.name}打卡页面`;$("#checkin-mark").style.background=p.color;$("#checkin-status").textContent=records(data[today()],p.id).length?"今天已有记录，可继续添加":"填写今天的打卡";$("#title-field").hidden=p.id!=="dance";["#checkin-title","#checkin-content","#checkin-minutes","#checkin-notes","#media-input"].forEach(s=>$(s).value="");$("#save-checkin").disabled=false;$("#save-checkin").textContent="保存记录";images($("#media-preview"),attachments,{editable:true,onRemove:removeImage});view("checkin-view");scrollTo(0,0)}
function closeCheckin(){clearURLs($("#media-preview"));activeProject=null;attachments=[];view("today-view");renderToday()}
function removeImage(id){attachments=attachments.filter(x=>x.id!==id);images($("#media-preview"),attachments,{editable:true,onRemove:removeImage})}
function selectImages(e){const files=[...e.target.files];e.target.value="";if(attachments.length+files.length>5)return alert("每条记录最多添加 5 张图片。");for(const file of files){if(!ALLOWED_IMAGE_TYPES.has(file.type))return alert(UNSUPPORTED_IMAGE_MESSAGE);if(file.size>10*1024*1024)return alert("请选择单张不超过 10MB 的图片。")}attachments.push(...files.map(file=>({id:uid(),name:file.name,type:file.type,size:file.size,file})));images($("#media-preview"),attachments,{editable:true,onRemove:removeImage})}
async function saveCheckin(){if(!activeProject||$("#save-checkin").disabled)return;const title=activeProject.id==="dance"?$("#checkin-title").value.trim():"",content=$("#checkin-content").value.trim(),minutes=Math.max(0,Number($("#checkin-minutes").value)||0),notes=$("#checkin-notes").value.trim();if(!(title||content||minutes||notes||attachments.length))return alert("请至少填写打卡内容、时间、备注或添加一张图片。");const b=$("#save-checkin");b.disabled=true;b.textContent="保存中…";try{if(attachments.length&&navigator.storage?.estimate){const q=await navigator.storage.estimate();if(q.quota&&q.usage+attachments.reduce((n,x)=>n+x.file.size,0)>q.quota*.9)throw Error("手机本地存储空间不足，请删除一些旧图片后重试。")}for(const x of attachments){const {file,...meta}=x;await saveImage({...meta,blob:file})}const d=today(),r={id:uid(),remote_id:null,owner_user_id:user.id,sync_status:"pending",sync_error:"",updated_at:new Date().toISOString(),record_date:d,category:activeProject.id,title,content,minutes,notes,note:notes,media:attachments.map(({file,...x})=>x)};data[d]||={};data[d][activeProject.id]=[...records(data[d],activeProject.id,true),r];await save();renderAll();$("#success-title").textContent=`${activeProject.name} 打卡成功`;$("#success-modal").hidden=false;if(navigator.onLine)sync?.syncAll()}catch(e){alert(e.message||"保存失败，请稍后重试。");b.disabled=false;b.textContent="保存记录"}}
function summary(day){const a=[];PROJECTS.slice(0,2).forEach(p=>{const r=records(day,p.id).filter(done);if(r.length)a.push({name:p.name,minutes:r.reduce((n,x)=>n+(+x.minutes||0),0),color:p.color})});const m=new Map();records(day,"dance").filter(done).forEach(r=>m.set(r.title||"杂七杂八",(m.get(r.title||"杂七杂八")||0)+(+r.minutes||0)));m.forEach((minutes,name)=>a.push({name,minutes,color:PROJECTS[2].color,misc:true}));return a}
function dates(){let a=Object.keys(data).filter(d=>has(data[d]));if(filter.applied){if(filter.date)a=a.filter(d=>d===filter.date);else if(filter.start||filter.end)a=a.filter(d=>(!filter.start||d>=filter.start)&&(!filter.end||d<=filter.end));else a=a.filter(d=>(!filter.year||d.slice(0,4)===filter.year)&&(!filter.month||+d.slice(5,7)===+filter.month))}return a.sort((a,b)=>filter.applied?a.localeCompare(b):b.localeCompare(a))}
function years(){const s=$("#filter-year"),v=s.value,a=[...new Set(Object.keys(data).filter(d=>has(data[d])).map(d=>d.slice(0,4)))].sort();s.replaceChildren(new Option("选择年份",""));a.forEach(y=>s.append(new Option(`${y}年`,y)));s.value=a.includes(v)?v:""}
function card(d){const b=document.createElement("button");b.className="history-row";b.type="button";const items=summary(data[d]),normal=items.filter(x=>!x.misc),misc=items.filter(x=>x.misc);b.innerHTML=`<header><time>${dateText(d)}</time><span class="history-chevron">›</span></header><div class="day-summary">${normal.map(x=>`<section class="day-project" style="--project:${x.color}"><strong>${esc(x.name)}</strong><span>${mins(x.minutes)}</span></section>`).join("")}${misc.length?`<section class="day-project day-project-misc" style="--project:${PROJECTS[2].color}"><strong>杂七杂八</strong><div class="misc-summary-list">${misc.map(x=>`<div><span>${esc(x.name)}</span><span>${mins(x.minutes)}</span></div>`).join("")}</div></section>`:""}</div>`;b.onclick=()=>detail(d);return b}
function detail(d){const out=$("#history-detail");out.querySelectorAll(".media-preview").forEach(clearURLs);out.replaceChildren();$("#history-day-heading").textContent=dateText(d);PROJECTS.forEach(p=>records(data[d],p.id).forEach(r=>{const a=document.createElement("article"),label=p.id==="dance"&&r.title?r.title:p.name;a.className="record-line";a.style.setProperty("--project",p.color);a.innerHTML=`<span class="project-tag${p.id==="dance"?" is-yellow":""}">${esc(label)}</span><strong>${esc(p.name)}${p.id==="dance"&&r.title?` · ${esc(r.title)}`:""} · ${mins(r.minutes)}</strong><span>${esc([r.content,r.notes??r.note].filter(Boolean).join("\n")||"未填写内容和备注")}</span>`;const del=document.createElement("button");del.className="record-delete";del.type="button";del.textContent="删除记录";del.onclick=async()=>{if(!confirm("确定删除这条记录吗？"))return;r.sync_status="pending_delete";r.deleted_at=new Date().toISOString();r.updated_at=r.deleted_at;await save();detail(d);renderAll();if(navigator.onLine)sync?.syncAll()};a.append(del);if(r.media?.length){const g=document.createElement("div");g.className="media-preview record-media";a.append(g);images(g,r.media)}out.append(a)}));view("history-day-view");scrollTo(0,0)}
function renderStats(){const list=$("#stats-list");list.replaceChildren();PROJECTS.forEach(p=>{const r=Object.keys(data).flatMap(d=>records(data[d],p.id)),m=r.reduce((n,x)=>n+(+x.minutes||0),0),days=Object.keys(data).filter(d=>records(data[d],p.id).some(done)).length,a=document.createElement("article");a.className="stat-card";a.style.setProperty("--project",p.color);a.innerHTML=`<header><h3>${p.name}</h3><strong>${mins(m)}</strong></header><p>累计练习 ${days} 天 · ${r.length} 条记录</p>`;list.append(a)})}
function renderHistory(){
  years();
  const status=$("#filter-status");
  status.hidden=!filter.applied;
  if(filter.applied)$("#filter-summary").textContent=filter.date?`筛选：${filter.date.replaceAll("-","/")}`:filter.start||filter.end?`筛选：${filter.start.replaceAll("-","/")||"最早"} - ${filter.end.replaceAll("-","/")||"今天"}`:filter.month?`筛选：${filter.year}年${filter.month}月`:`筛选：${filter.year}年`;
  const list=$("#history-list"),items=dates(),months=[...new Set(items.map(date=>date.slice(0,7)))];
  list.replaceChildren();
  $("#month-jump").hidden=true;
  if(!items.length){list.innerHTML='<p class="empty">没有符合条件的打卡记录。</p>';return}
  const yearOnly=filter.applied&&filter.year&&!filter.month&&!filter.date&&!filter.start&&!filter.end;
  const rangeAcrossMonths=filter.applied&&(filter.start||filter.end)&&months.length>1;
  if(!yearOnly&&!rangeAcrossMonths){items.forEach(date=>list.append(card(date)));return}
  const groups=new Map(),crossYear=new Set(items.map(date=>date.slice(0,4))).size>1,jump=$("#month-jump");
  items.forEach(date=>{const month=date.slice(0,7);groups.set(month,[...(groups.get(month)||[]),date])});
  jump.replaceChildren();
  groups.forEach((monthDates,month)=>{const section=document.createElement("section");section.className="month-group";section.id=`month-${month}`;section.innerHTML=`<h3 class="month-heading">${monthText(month)}</h3>`;monthDates.forEach(date=>section.append(card(date)));list.append(section);const button=document.createElement("button");button.textContent=crossYear?monthText(month):`${Number(month.slice(5))}月`;button.onclick=()=>section.scrollIntoView({behavior:"smooth"});jump.append(button)});
  jump.hidden=false;
}
function renderAll(){renderToday();renderHistory();renderStats()}
function mode(m){filterMode=m;document.querySelectorAll("[data-filter-mode]").forEach(b=>b.classList.toggle("is-active",b.dataset.filterMode===m));$("#filter-year-field").hidden=!['year','month'].includes(m);$("#filter-month-field").hidden=m!=="month";$("#filter-date-field").hidden=m!=="date";$("#filter-start-field").hidden=m!=="range";$("#filter-end-field").hidden=m!=="range"}
function clearFilter(){["#filter-year","#filter-month","#filter-date","#filter-start","#filter-end"].forEach(s=>$(s).value="");filter={applied:false,year:"",month:"",date:"",start:"",end:""};renderHistory();$("#filter-sheet").hidden=true}
function applyFilter(){const v={year:$("#filter-year").value,month:$("#filter-month").value,date:$("#filter-date").value,start:$("#filter-start").value,end:$("#filter-end").value};if(filterMode==="year"&&!v.year)return alert("请选择年份。");if(filterMode==="month"&&(!v.year||!v.month))return alert("请选择年份和月份。");if(filterMode==="date"&&!v.date)return alert("请选择日期。");if(filterMode==="range"&&(!v.start&&!v.end||v.start&&v.end&&v.start>v.end))return alert("请填写有效的时间段。");filter={applied:true,...v};if(filterMode==="year")Object.assign(filter,{month:"",date:"",start:"",end:""});if(filterMode==="month")Object.assign(filter,{date:"",start:"",end:""});if(filterMode==="date")Object.assign(filter,{year:"",month:"",start:"",end:""});if(filterMode==="range")Object.assign(filter,{year:"",month:"",date:""});renderHistory();$("#filter-sheet").hidden=true}
function syncStatus(s){const b=$("#sync-status");if(!user){b.hidden=true;return}b.hidden=false;b.textContent=s.state==="offline"?`离线模式${s.count?` · ${s.count} 条待同步`:""}`:s.state==="expired"?"登录已过期":s.state==="syncing"?"正在同步…":s.state==="pending"?`${s.count} 条等待同步`:s.state==="failed"?"同步失败":"已同步"}
async function loadAccount(u,offline=false){user=u;data=await stateGet(key(u.id))||{};let changed=normaliseAccountRecords(data,u.id);await claimImageCache(data,u.id);if(!Object.keys(data).length){const legacy=await stateGet("records")||{},legacyOwner=await stateGet("legacyOwnerUid");if(Object.keys(legacy).length&&(!legacyOwner||legacyOwner===u.id)&&confirm("发现本机已有历史记录，是否同步到云端？")){if(!legacyOwner)await statePut("legacyOwnerUid",u.id);data=JSON.parse(JSON.stringify(legacy));normaliseAccountRecords(data,u.id);await claimImageCache(data,u.id);changed=true}}if(changed)await save();sync=offline?null:createSyncService({getRecords:()=>data,saveRecords:save,getImage,saveImage,deleteImages,ownerId:u.id,onStatus:syncStatus,onChanged:renderAll});$("#account-email").textContent=u.email||u.id;$("#auth-gate").hidden=true;renderAll();if(offline)syncStatus({state:"offline",count:pendingCount()});else{syncStatus({state:"syncing"});sync.syncAll()}}
async function rememberAndLoad(u){await statePut("lastAuthenticatedUser",{id:u.id,email:u.email||""});await loadAccount(u)}
async function resumeOnline(){if(!user)return;try{const cloudUser=await getCurrentUser();if(!cloudUser||cloudUser.id!==user.id){await statePut("lastAuthenticatedUser",null);syncStatus({state:"expired"});alert("登录已过期，请重新登录后同步。");authScreen("登录已过期，请重新登录后同步。");return}await rememberAndLoad(cloudUser)}catch(error){syncStatus({state:"offline",count:pendingCount()});console.warn("暂时无法验证云端登录状态",error)}}
async function logout(){if(!user)return;if(!navigator.onLine){if(!confirm("当前处于离线状态。仅退出本机登录吗？未同步的数据会继续保存在本机。"))return;await statePut("lastAuthenticatedUser",null);authScreen("已退出本机账号。未同步数据仍保存在本机。");return}try{await signOut();await statePut("lastAuthenticatedUser",null);authScreen("已退出登录。")}catch(error){console.warn("云端退出失败",error);alert("退出登录失败，请检查网络后重试。")} }
function authScreen(msg=""){user=null;data={};sync=null;pendingSignUp=null;registerMode=false;$("#account-sheet").hidden=true;$("#auth-gate").hidden=false;$("#auth-message").textContent=msg;authMode();syncStatus({})}
function authMode(){const verifying=!!pendingSignUp;$("#auth-email-field").hidden=verifying;$("#auth-password-field").hidden=verifying;$("#auth-otp-field").hidden=!verifying;$("#auth-submit").textContent=verifying?"验证并完成注册":registerMode?"注册并发送验证码":"登录";$("#auth-switch").textContent=verifying||registerMode?"返回登录":"注册新账号";$("#auth-copy").textContent=verifying?`验证码已发送至 ${pendingSignUp.email}`:registerMode?"输入邮箱和密码后，我们会发送注册验证码。":"登录后安全同步你的成长记录。";$("#auth-password").autocomplete=registerMode?"new-password":"current-password"}
async function submit(){const b=$("#auth-submit");b.disabled=true;try{if(pendingSignUp){const token=$("#auth-otp").value.trim();if(!token)throw Error("请输入邮箱收到的验证码。");const verified=await verifySignUpOtp(pendingSignUp.result,token);const u=verified?.user||verified?.session?.user||await getCurrentUser();if(!u)throw Error("验证码已通过，但未取得用户信息，请重试。");pendingSignUp=null;registerMode=false;await rememberAndLoad(u);return}const email=$("#auth-email").value.trim(),password=$("#auth-password").value;if(!email||!password)throw Error("请输入邮箱和密码。");if(registerMode){const result=await signUpWithEmail(email,password);if(typeof result?.verifyOtp!=="function")throw Error("CloudBase 未返回验证码验证流程，请检查邮箱注册配置。");pendingSignUp={email,result};$("#auth-otp").value="";$("#auth-message").textContent="请输入邮箱收到的验证码。";authMode();$("#auth-otp").focus()}else{await signInWithEmail(email,password);const u=await getCurrentUser();if(!u)throw Error("未取得用户信息，请重试。");await rememberAndLoad(u)}}catch(e){$("#auth-message").textContent=e.message||"认证失败，请重试。"}finally{b.disabled=false}}

document.querySelectorAll(".tab[data-view]").forEach(b=>b.onclick=()=>{if(activeProject)closeCheckin();view(b.dataset.view)});$("#back-home").onclick=closeCheckin;$("#back-history").onclick=()=>view("history-view");$("#open-filter").onclick=()=>{years();mode(filter.date?"date":filter.start||filter.end?"range":filter.month?"month":"year");$("#filter-sheet").hidden=false};$("#close-filter").onclick=()=>$("#filter-sheet").hidden=true;$("#filter-sheet").onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.hidden=true};document.querySelectorAll("[data-filter-mode]").forEach(b=>b.onclick=()=>mode(b.dataset.filterMode));$("#apply-filter").onclick=applyFilter;$("#clear-filter").onclick=clearFilter;$("#quick-clear-filter").onclick=clearFilter;$("#media-input").onchange=selectImages;$("#save-checkin").onclick=saveCheckin;$("#success-modal").onclick=e=>{if(e.target===e.currentTarget){$("#success-modal").hidden=true;closeCheckin()}};$("#success-modal .modal-close").onclick=()=>{$("#success-modal").hidden=true;closeCheckin()};$("#media-viewer").onclick=e=>{if(e.target===e.currentTarget)closeViewer()};$("#media-viewer .viewer-close").onclick=closeViewer;$("#auth-switch").onclick=()=>{registerMode=!registerMode;authMode()};$("#auth-submit").onclick=submit;$("#account-button").onclick=()=>$("#account-sheet").hidden=false;$("#close-account").onclick=()=>$("#account-sheet").hidden=true;$("#account-sheet").onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.hidden=true};$("#sync-status").onclick=()=>sync?sync.syncAll():navigator.onLine&&resumeOnline();$("#account-sync").onclick=()=>navigator.onLine?resumeOnline():syncStatus({state:"offline",count:pendingCount()});$("#logout").onclick=logout;addEventListener("offline",()=>{sync=null;syncStatus({state:"offline",count:pendingCount()})});addEventListener("online",resumeOnline);if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js",{scope:"./"}));
$("#auth-switch").onclick=()=>{if(pendingSignUp){pendingSignUp=null;registerMode=false;$("#auth-otp").value=""}else registerMode=!registerMode;$("#auth-message").textContent="";authMode()};
(async()=>{await storage();authMode();if(!isCloudbaseConfigured())return authScreen(cloudbaseConfigurationMessage());try{initialiseCloudbase()}catch(error){authScreen(error.message||"CloudBase 初始化失败。");return}const lastUser=await stateGet("lastAuthenticatedUser");if(!navigator.onLine){lastUser?await loadAccount(lastUser,true):authScreen("当前离线，请先联网登录一次。");return}try{const cloudUser=await getCurrentUser();if(cloudUser)await rememberAndLoad(cloudUser);else{await statePut("lastAuthenticatedUser",null);authScreen()}}catch(error){if(lastUser)await loadAccount(lastUser,true);else authScreen("暂时无法验证登录状态，请检查网络后重试。")}})();
